version: 0.2
env:
  parameter-store:
    GOOS: "GOOS"
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install apache2 -y
      - service apache2 start
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build ./lab_01/hello.go
  post_build:
    commands:
      - ./hello > /var/www/html/index2.html
      - cat /var/www/html/index2.html
      - aws s3 cp index.html s3://pappgeztest/www/index.html
artifacts:
  files:
    - hello
