version: 0.2
env:
  parameter-store:
    GOOS: "GOOS"
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build ./lab_01/hello.go
artifacts:
  files:
    - hello
